app:
  pool: 100
  port: 80
log:
  env: dev
  level: info
kafka:
  version: "2.5.0"
  timeout: 10s
  group: "kafka.group"
  auth: false
  topic:
    consumeTopic: 
      - "InsuranceCallBack"
      - "PaymentcallBack"
  brokers:
    - "localhost:9092"
    # - "brokers2:9092"
    # - "brokers3:9092"

db:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: myPassword
  database: mydataBase
  parseTime: true
# secrets:
#   kafkaUsername: "sit_msg_cdi"
#   kafkaPassword: "IVUWDLIgVauVwJG"